import type { AiMode } from "./types";

/** career-ops modes exposed in AI Studio (see career-ops/.claude/skills/career-ops/SKILL.md). */
export const AI_MODES: AiMode[] = [
  { id: "auto-pipeline", label: "Evaluate + tailor CV", group: "Evaluate", description: "Full A–G evaluation report, tailored ATS CV PDF, and a tracker row.", needs: ["job"] },
  { id: "triage", label: "Quick triage", group: "Evaluate", description: "Fast first-pass filter: is this worth a full evaluation?", needs: ["job"] },
  { id: "oferta", label: "Evaluate only (report)", group: "Evaluate", description: "A–G evaluation report without generating a PDF.", needs: ["job"] },
  { id: "pdf", label: "Tailored CV (PDF)", group: "Apply", description: "ATS-optimised CV tailored to this job, from cv.md. Never invents experience.", needs: ["job"] },
  { id: "cover", label: "Cover letter", group: "Apply", description: "Research-backed cover letter + A4 PDF.", needs: ["job"] },
  { id: "email", label: "Application email", group: "Apply", description: "Formal application email draft with subject, body, attachment checklist.", needs: ["job"] },
  { id: "contacto", label: "LinkedIn outreach", group: "Apply", description: "Find the recruiter / hiring manager and draft a connection message.", needs: ["job"] },
  { id: "apply", label: "Application form answers", group: "Apply", description: "Draft answers for the application form questions (you paste and submit).", needs: ["job"] },
  { id: "deep", label: "Company deep research", group: "Research", description: "6-axis research: strategy, recent moves, engineering culture, challenges, competitors, your angle.", needs: ["company"] },
  { id: "interview-redflag", label: "Red-flag check", group: "Research", description: "Is this company safe to join? Red-flag analysis.", needs: ["company"] },
  { id: "interview-prep", label: "Interview prep", group: "Interview", description: "Company-specific interview intel and likely questions.", needs: ["job"] },
  { id: "interview/plan", label: "Prep plan", group: "Interview", description: "Time-blocked prep plan for an upcoming interview.", needs: ["job"] },
  { id: "interview/debrief", label: "Debrief", group: "Interview", description: "After a real interview: log the questions, spot gaps, update the story bank.", needs: ["job"], input: "What happened in the interview", inputHint: "Round, interviewer, the questions asked, where you felt weak…" },
  { id: "ofertas", label: "Compare offers", group: "Evaluate", description: "Side-by-side comparison of several evaluated jobs with a recommendation.", needs: ["none"], input: "Which jobs to compare", inputHint: "e.g. reports 012, 015 and 019 — or company names from your tracker" },
  { id: "offer-prep", label: "Understand an offer", group: "Offer", description: "Clause-by-clause walk through an offer/contract, questions for a lawyer, and items to raise. Describes, never judges.", needs: ["none"], input: "Offer or contract text", inputHint: "Paste the offer letter / contract, or a path to it inside career-ops (e.g. documents/offer.pdf)" },
  { id: "followup", label: "Follow-ups due", group: "Track", description: "Which applications need a follow-up now, with drafted follow-up messages.", needs: ["none"] },
  { id: "reply-watch", label: "Classify a reply", group: "Track", description: "Classify a recruiter/company email, match it to an application, and suggest the tracker update.", needs: ["none"], input: "The email", inputHint: "Paste subject, sender and body" },
  { id: "outcome", label: "Record outcome", group: "Track", description: "Record how an application ended and archive its report, CV and posting.", needs: ["none"], input: "Which application and what happened", inputHint: "e.g. #14 HighLevel — rejected after the 2nd round" },
  { id: "patterns", label: "Rejection patterns", group: "Track", description: "What your advancing applications have in common, and what to change in targeting.", needs: ["none"] },
  { id: "pipeline", label: "Process pipeline inbox", group: "Track", description: "Evaluate every pending URL in data/pipeline.md (reports + tracker rows).", needs: ["none"] },
  { id: "titles", label: "Adjacent job titles", group: "Profile", description: "Suggest more job titles to search for, based on your CV.", needs: ["none"] },
  { id: "expand", label: "Find missing competencies", group: "Profile", description: "Discover CV competencies you forgot to write down (proposes, never auto-writes).", needs: ["none"] },
  { id: "upskill", label: "What to learn next", group: "Profile", description: "Skill-gap analysis across your evaluated pipeline.", needs: ["none"] },
  { id: "add", label: "Add to CV", group: "Profile", description: "Add a finished project, paper or role to cv.md (source-grounded; shows a preview in the run log).", needs: ["none"], input: "What to add", inputHint: "Project name, what you built, stack, results, links…" },
  { id: "intake", label: "Profile intake", group: "Profile", description: "Read your documents/ folder (master CV, LinkedIn export…) and propose profile additions. Proposes only.", needs: ["none"] },
  { id: "training", label: "Evaluate a course", group: "Profile", description: "Is this course or certification worth your time for your target roles?", needs: ["none"], input: "Course or certification", inputHint: "Name and link" },
  { id: "project", label: "Evaluate a project idea", group: "Profile", description: "Would this portfolio project help you land your target roles?", needs: ["none"], input: "Project idea", inputHint: "What it does, stack, how long it would take" },
  { id: "discover", label: "Find company job boards", group: "Research", description: "Resolve company names to their ATS boards and add them to portals.yml for the scanner.", needs: ["none"], input: "Companies", inputHint: "One per line" },
  { id: "custom", label: "Custom prompt", group: "Profile", description: "Any career-ops request in your own words.", needs: ["none"], input: "Prompt", inputHint: "e.g. Compare my last 3 evaluated offers and tell me which to prioritise" },
];
